export interface BlogPost {
  slug: string;
  titleKey: string;
  excerptKey: string;
  contentKey: string;
  date: string;
  readTime: string;
  category: string;
  accentColor: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "why-your-business-needs-a-website-in-2025",
    titleKey: "post1Title",
    excerptKey: "post1Excerpt",
    contentKey: "post1Content",
    date: "2025-01-15",
    readTime: "5 min",
    category: "BUSINESS",
    accentColor: "neo-lime",
  },
  {
    slug: "seo-basics-for-small-businesses",
    titleKey: "post2Title",
    excerptKey: "post2Excerpt",
    contentKey: "post2Content",
    date: "2025-01-28",
    readTime: "7 min",
    category: "SEO",
    accentColor: "neo-yellow",
  },
  {
    slug: "nextjs-vs-wordpress-which-is-better",
    titleKey: "post3Title",
    excerptKey: "post3Excerpt",
    contentKey: "post3Content",
    date: "2025-02-10",
    readTime: "6 min",
    category: "TECH",
    accentColor: "neo-blue",
  },
  {
    slug: "how-to-increase-website-conversion-rate",
    titleKey: "post4Title",
    excerptKey: "post4Excerpt",
    contentKey: "post4Content",
    date: "2025-02-25",
    readTime: "8 min",
    category: "MARKETING",
    accentColor: "neo-pink",
  },
  {
    slug: "multilingual-websites-expand-your-reach",
    titleKey: "post5Title",
    excerptKey: "post5Excerpt",
    contentKey: "post5Content",
    date: "2025-03-10",
    readTime: "5 min",
    category: "GROWTH",
    accentColor: "neo-green",
  },
  {
    slug: "how-much-does-a-website-cost-in-europe",
    titleKey: "post6Title",
    excerptKey: "post6Excerpt",
    contentKey: "post6Content",
    date: "2025-03-25",
    readTime: "8 min",
    category: "BUSINESS",
    accentColor: "neo-lime",
  },
  {
    slug: "web-design-trends-2025",
    titleKey: "post7Title",
    excerptKey: "post7Excerpt",
    contentKey: "post7Content",
    date: "2025-04-08",
    readTime: "6 min",
    category: "DESIGN",
    accentColor: "neo-purple",
  },
  {
    slug: "why-french-businesses-need-a-professional-website",
    titleKey: "post8Title",
    excerptKey: "post8Excerpt",
    contentKey: "post8Content",
    date: "2025-04-22",
    readTime: "7 min",
    category: "BUSINESS",
    accentColor: "neo-orange",
  },
  {
    slug: "ecommerce-guide-for-belgian-businesses",
    titleKey: "post9Title",
    excerptKey: "post9Excerpt",
    contentKey: "post9Content",
    date: "2025-05-05",
    readTime: "9 min",
    category: "E-COMMERCE",
    accentColor: "neo-pink",
  },
  {
    slug: "seo-tips-for-uk-small-businesses",
    titleKey: "post10Title",
    excerptKey: "post10Excerpt",
    contentKey: "post10Content",
    date: "2025-05-18",
    readTime: "7 min",
    category: "SEO",
    accentColor: "neo-yellow",
  },
  {
    slug: "website-speed-optimization-guide",
    titleKey: "post11Title",
    excerptKey: "post11Excerpt",
    contentKey: "post11Content",
    date: "2025-06-01",
    readTime: "8 min",
    category: "TECH",
    accentColor: "neo-blue",
  },
  {
    slug: "how-to-choose-a-web-development-agency",
    titleKey: "post12Title",
    excerptKey: "post12Excerpt",
    contentKey: "post12Content",
    date: "2025-06-15",
    readTime: "6 min",
    category: "BUSINESS",
    accentColor: "neo-green",
  },
  {
    slug: "react-vs-wordpress-for-business-websites",
    titleKey: "post13Title",
    excerptKey: "post13Excerpt",
    contentKey: "post13Content",
    date: "2025-06-28",
    readTime: "7 min",
    category: "TECH",
    accentColor: "neo-lime",
  },
  {
    slug: "gdpr-compliant-website-checklist",
    titleKey: "post14Title",
    excerptKey: "post14Excerpt",
    contentKey: "post14Content",
    date: "2025-07-10",
    readTime: "9 min",
    category: "LEGAL",
    accentColor: "neo-orange",
  },
  {
    slug: "local-seo-strategy-for-european-businesses",
    titleKey: "post15Title",
    excerptKey: "post15Excerpt",
    contentKey: "post15Content",
    date: "2025-07-24",
    readTime: "8 min",
    category: "SEO",
    accentColor: "neo-purple",
  },
];
