export interface ProjectMetrics {
  lighthouse: number;
  loadTime: string;
  improvement: string;
}

export interface ProjectTestimonial {
  quoteKey: string;
  nameKey: string;
  roleKey: string;
}

export interface Project {
  id: string;
  num: string;
  name: string;
  sectorKey: string;
  country: "FR" | "BE" | "UK" | "INT";
  countryNameKey: string;
  flag: string;
  url: string;
  tech: string[];
  accentColor: string;
  descriptionKey: string;
  category: "web" | "ecommerce" | "branding";
  year: string;
  challengeKey: string;
  solutionKey: string;
  resultsKeys: string[];
  metrics: ProjectMetrics;
  testimonial?: ProjectTestimonial;
  featured: boolean;
  imageDesktop?: string;
  imageMobile?: string;
  imageBefore?: string;
}

export const projects: Project[] = [
  {
    id: "cakir-facades",
    num: "01",
    name: "CAKIR FACADES",
    sectorKey: "projects.cakir.sector",
    country: "FR",
    countryNameKey: "projects.cakir.country",
    flag: "\u{1F1EB}\u{1F1F7}",
    url: "https://cakirfacades.fr",
    imageDesktop: "/portfolio/cakir-desktop.webp",
    imageMobile: "/portfolio/cakir-mobile.webp",
    tech: ["React", "Vite", "Tailwind"],
    accentColor: "neo-lime",
    descriptionKey: "projects.cakir.description",
    category: "web",
    year: "2024",
    challengeKey: "projects.cakir.challenge",
    solutionKey: "projects.cakir.solution",
    resultsKeys: ["projects.cakir.result1", "projects.cakir.result2", "projects.cakir.result3"],
    metrics: { lighthouse: 96, loadTime: "<1.4s", improvement: "+40%" },
    testimonial: {
      quoteKey: "projects.cakir.testimonialQuote",
      nameKey: "projects.cakir.testimonialName",
      roleKey: "projects.cakir.testimonialRole",
    },
    featured: true,
  },
  {
    id: "altinbas-moustiquaire",
    num: "02",
    name: "ALTINBAS",
    sectorKey: "projects.altinbas.sector",
    country: "FR",
    countryNameKey: "projects.altinbas.country",
    flag: "\u{1F1EB}\u{1F1F7}",
    url: "https://altinbasmoustiquaire.fr",
    imageDesktop: "/portfolio/altinbas-desktop.webp",
    imageMobile: "/portfolio/altinbas-mobile.webp",
    tech: ["React", "Vite", "Tailwind"],
    accentColor: "neo-yellow",
    descriptionKey: "projects.altinbas.description",
    category: "ecommerce",
    year: "2024",
    challengeKey: "projects.altinbas.challenge",
    solutionKey: "projects.altinbas.solution",
    resultsKeys: ["projects.altinbas.result1", "projects.altinbas.result2", "projects.altinbas.result3"],
    metrics: { lighthouse: 94, loadTime: "<1.6s", improvement: "+55%" },
    testimonial: {
      quoteKey: "projects.altinbas.testimonialQuote",
      nameKey: "projects.altinbas.testimonialName",
      roleKey: "projects.altinbas.testimonialRole",
    },
    featured: true,
  },
  {
    id: "consulting-energy",
    num: "03",
    name: "CONSULTING ENERGY",
    sectorKey: "projects.consulting.sector",
    country: "FR",
    countryNameKey: "projects.consulting.country",
    flag: "\u{1F1EB}\u{1F1F7}",
    url: "https://consulting-energy.fr",
    imageDesktop: "/portfolio/consulting-desktop.webp",
    imageMobile: "/portfolio/consulting-mobile.webp",
    tech: ["React", "Vite", "TypeScript"],
    accentColor: "neo-blue",
    descriptionKey: "projects.consulting.description",
    category: "web",
    year: "2024",
    challengeKey: "projects.consulting.challenge",
    solutionKey: "projects.consulting.solution",
    resultsKeys: ["projects.consulting.result1", "projects.consulting.result2", "projects.consulting.result3"],
    metrics: { lighthouse: 97, loadTime: "<1.2s", improvement: "+35%" },
    testimonial: {
      quoteKey: "projects.consulting.testimonialQuote",
      nameKey: "projects.consulting.testimonialName",
      roleKey: "projects.consulting.testimonialRole",
    },
    featured: true,
  },
  {
    id: "iso-home-energy",
    num: "04",
    name: "ISO HOME ENERGY",
    sectorKey: "projects.iso.sector",
    country: "FR",
    countryNameKey: "projects.iso.country",
    flag: "\u{1F1EB}\u{1F1F7}",
    url: "https://ih-energy.fr",
    imageDesktop: "/portfolio/iso-desktop.webp",
    imageMobile: "/portfolio/iso-mobile.webp",
    tech: ["React", "Vite", "TypeScript", "Tailwind"],
    accentColor: "neo-green",
    descriptionKey: "projects.iso.description",
    category: "web",
    year: "2024",
    challengeKey: "projects.iso.challenge",
    solutionKey: "projects.iso.solution",
    resultsKeys: ["projects.iso.result1", "projects.iso.result2", "projects.iso.result3"],
    metrics: { lighthouse: 95, loadTime: "<1.5s", improvement: "+45%" },
    testimonial: {
      quoteKey: "projects.iso.testimonialQuote",
      nameKey: "projects.iso.testimonialName",
      roleKey: "projects.iso.testimonialRole",
    },
    featured: true,
  },
  {
    id: "archi-construction",
    num: "05",
    name: "ARCHI CONSTRUCTION",
    sectorKey: "projects.archi.sector",
    country: "BE",
    countryNameKey: "projects.archi.country",
    flag: "\u{1F1E7}\u{1F1EA}",
    url: "https://archi.constructionveranda.com",
    imageDesktop: "/portfolio/archi-desktop.webp",
    imageMobile: "/portfolio/archi-mobile.webp",
    tech: ["React", "Vite", "TypeScript", "Tailwind"],
    accentColor: "neo-pink",
    descriptionKey: "projects.archi.description",
    category: "web",
    year: "2024",
    challengeKey: "projects.archi.challenge",
    solutionKey: "projects.archi.solution",
    resultsKeys: ["projects.archi.result1", "projects.archi.result2", "projects.archi.result3"],
    metrics: { lighthouse: 95, loadTime: "<1.5s", improvement: "+60%" },
    testimonial: {
      quoteKey: "projects.archi.testimonialQuote",
      nameKey: "projects.archi.testimonialName",
      roleKey: "projects.archi.testimonialRole",
    },
    featured: true,
  },
  {
    id: "adamsons",
    num: "06",
    name: "ADAMSONS ACCOUNTANTS",
    sectorKey: "projects.adamsons.sector",
    country: "UK",
    countryNameKey: "projects.adamsons.country",
    flag: "\u{1F1EC}\u{1F1E7}",
    url: "https://adamsons.uk.com",
    imageDesktop: "/portfolio/adamsons-desktop.webp",
    imageMobile: "/portfolio/adamsons-mobile.webp",
    tech: ["React", "Vite", "Tailwind"],
    accentColor: "neo-purple",
    descriptionKey: "projects.adamsons.description",
    category: "web",
    year: "2024",
    challengeKey: "projects.adamsons.challenge",
    solutionKey: "projects.adamsons.solution",
    resultsKeys: ["projects.adamsons.result1", "projects.adamsons.result2", "projects.adamsons.result3"],
    metrics: { lighthouse: 98, loadTime: "<1.1s", improvement: "+25%" },
    testimonial: {
      quoteKey: "projects.adamsons.testimonialQuote",
      nameKey: "projects.adamsons.testimonialName",
      roleKey: "projects.adamsons.testimonialRole",
    },
    featured: true,
  },
  {
    id: "ata-accountancy",
    num: "07",
    name: "ATA ACCOUNTANCY",
    sectorKey: "projects.ata.sector",
    country: "UK",
    countryNameKey: "projects.ata.country",
    flag: "\u{1F1EC}\u{1F1E7}",
    url: "http://ataaccountancy.com",
    imageDesktop: "/portfolio/ata-desktop.webp",
    imageMobile: "/portfolio/ata-mobile.webp",
    tech: ["React", "Vite", "Tailwind"],
    accentColor: "neo-blue",
    descriptionKey: "projects.ata.description",
    category: "web",
    year: "2024",
    challengeKey: "projects.ata.challenge",
    solutionKey: "projects.ata.solution",
    resultsKeys: ["projects.ata.result1", "projects.ata.result2", "projects.ata.result3"],
    metrics: { lighthouse: 97, loadTime: "<1.2s", improvement: "+30%" },
    featured: false,
  },
  {
    id: "idhome-travaux",
    num: "08",
    name: "ID HOME",
    sectorKey: "projects.idhome.sector",
    country: "FR",
    countryNameKey: "projects.idhome.country",
    flag: "\u{1F1EB}\u{1F1F7}",
    url: "https://idhome-travaux.fr",
    imageDesktop: "/portfolio/idhome-desktop.webp",
    imageMobile: "/portfolio/idhome-mobile.webp",
    tech: ["React", "Vite", "Tailwind"],
    accentColor: "neo-orange",
    descriptionKey: "projects.idhome.description",
    category: "web",
    year: "2025",
    challengeKey: "projects.idhome.challenge",
    solutionKey: "projects.idhome.solution",
    resultsKeys: ["projects.idhome.result1", "projects.idhome.result2", "projects.idhome.result3"],
    metrics: { lighthouse: 96, loadTime: "<1.4s", improvement: "+45%" },
    featured: false,
  },
  {
    id: "gmg-design",
    num: "09",
    name: "GMG DESIGN",
    sectorKey: "projects.gmg.sector",
    country: "INT",
    countryNameKey: "projects.gmg.country",
    flag: "\u{1F30D}",
    url: "https://dmckreatif.com",
    imageDesktop: "/portfolio/gmg-desktop.webp",
    imageMobile: "/portfolio/gmg-mobile.webp",
    tech: ["Next.js", "Tailwind", "Framer Motion", "next-intl"],
    accentColor: "neo-lime",
    descriptionKey: "projects.gmg.description",
    category: "branding",
    year: "2024",
    challengeKey: "projects.gmg.challenge",
    solutionKey: "projects.gmg.solution",
    resultsKeys: ["projects.gmg.result1", "projects.gmg.result2", "projects.gmg.result3"],
    metrics: { lighthouse: 96, loadTime: "<1.3s", improvement: "+50%" },
    featured: false,
  },
  {
    id: "mkn-technisch",
    num: "10",
    name: "MKN TECHNISCH",
    sectorKey: "projects.mkn.sector",
    country: "BE",
    countryNameKey: "projects.mkn.country",
    flag: "\u{1F1E7}\u{1F1EA}",
    url: "https://mkntechnisch.com",
    imageDesktop: "/portfolio/mkn-desktop.webp",
    imageMobile: "/portfolio/mkn-mobile.webp",
    tech: ["React", "Vite", "Tailwind"],
    accentColor: "neo-yellow",
    descriptionKey: "projects.mkn.description",
    category: "web",
    year: "2025",
    challengeKey: "projects.mkn.challenge",
    solutionKey: "projects.mkn.solution",
    resultsKeys: ["projects.mkn.result1", "projects.mkn.result2", "projects.mkn.result3"],
    metrics: { lighthouse: 95, loadTime: "<1.5s", improvement: "+50%" },
    featured: false,
  },
  {
    id: "retro-kosar",
    num: "11",
    name: "RETRO KO\u015EAR TEKST\u0130L",
    sectorKey: "projects.retro.sector",
    country: "FR",
    countryNameKey: "projects.retro.country",
    flag: "\u{1F1EB}\u{1F1F7}",
    url: "https://retrokosartekstil.com/fr",
    imageDesktop: "/portfolio/retro-desktop.webp",
    imageMobile: "/portfolio/retro-mobile.webp",
    tech: ["React", "Vite", "TypeScript", "Tailwind", "i18next"],
    accentColor: "neo-pink",
    descriptionKey: "projects.retro.description",
    category: "ecommerce",
    year: "2025",
    challengeKey: "projects.retro.challenge",
    solutionKey: "projects.retro.solution",
    resultsKeys: ["projects.retro.result1", "projects.retro.result2", "projects.retro.result3"],
    metrics: { lighthouse: 95, loadTime: "<1.5s", improvement: "+55%" },
    featured: false,
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
